package com.twproject.banyeomiji.view.main.datamodel

data class PetLocationData(
    val BULD_NO: Any = 0 ,
    val CTGRY_ONE_NM: String = "",
    val CTGRY_THREE_NM: String = "",
    val CTGRY_TWO_NM: String = "",
    val CTPRVN_NM: String = "",
    val ENTRN_POSBL_PET_SIZE_VALUE: String = "",
    val FCLTY_INFO_DC: String = "",
    val FCLTY_NM: String = "",
    val HMPG_URL: String = "",
    val IN_PLACE_ACP_POSBL_AT: String = "",
    val LAST_UPDT_DE: Long = 0L,
    val LC_LA: Double = 0.0,
    val LC_LO: Double = 0.0,
    val LEGALDONG_NM: String = "",
    val LI_NM: String = "",
    val LNBR_NO: String = "",
    val LNM_ADDR: String = "",
    val OPER_TIME: String = "",
    val OUT_PLACE_ACP_POSBL_AT: String = "",
    val PARKNG_POSBL_AT: String = "",
    val PET_ACP_ADIT_CHRGE_VALUE: String = "",
    val PET_INFO_CN: String = "",
    val PET_LMTT_MTR_CN: String = "",
    val PET_POSBL_AT: String = "",
    val RDNMADR_NM: String = "",
    val ROAD_NM: String = "",
    val RSTDE_GUID_CN: String = "",
    val SIGNGU_NM: String = "",
    val TEL_NO: Any = 0,
    val UTILIIZA_PRC_CN: String = "",
    val ZIP_NO: Any = 0,
    val DOC_ID: String = "",
    val USER_REVIEW: Map<String, Any> = mapOf()
)